routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/

Route::get('/', 'PublicPagesController@home');
Route::get('/portfolio', 'PublicPagesController@portfolio')->name('portfolio');
Route::get('/resume', 'PublicPagesController@resume');
Route::get('/services', 'PublicPagesController@services');
Route::get('/modeling', 'PublicPagesController@modeling');
Route::get('/project/{project}', 'ProjectController@show');
Route::get('/project/slug/{project_slug}', 'ProjectController@slug')->name('project.show');
Route::get('/contact', 'PublicPagesController@contact');


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Image.php
<?php

namespace App;

use App\Project;
use Illuminate\Database\Eloquent\Model;

class Image extends Model
{

    protected $guarded = ['id'];

    public function project(){
    	return $this->belongsTo(Project::class, 'relation_id');
    }

    public function getPublicUrlAttribute(){
    	return "https://poncianodiego.com/storage/" . $this->attributes['url'];
    }
}

app/Partner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    public function isNone(){
    
    	return $this->name == "None";
    	
    }

    public function projects(){
    
    	return $this->hasMany(Project::class);
    	
    }
}

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    //
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Post extends Model
{
    
}

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{

    const STATUS_DRAFT = 0;
    const STATUS_PUBLISHED = 1;

    protected $guarded = ['id'];

    protected $statusLabels = [
        self::STATUS_DRAFT => 'Draft',
        self::STATUS_PUBLISHED => 'Published'
    ];

    public function getStatusAttribute(){
        return self::statusLabels[$this->status_id]; 
    }

    public function getNakedUrlAttribute(){
    
    	return preg_replace("#^http(s)?://#", '', $this->internal_url);
    	
    }

    public function getPublicThumbnailAttribute(){
    
    	return "https://poncianodiego.com/storage/" . $this->attributes['thumbnail'];
    	
    }

    public function getInternalUrlAttribute(){
        return route('project.show', $this->slug);
    }

    public function partner(){
    
    	return $this->belongsTo(Partner::class);
    	
    }

    public function images(){
        return $this->hasMany(Image::class, 'relation_id');
    }

    public function scopePublished($query){
        return $query->where('status_id', self::STATUS_PUBLISHED);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends \TCG\Voyager\Models\User
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ExampleController.php
<?php

namespace App\Http\Controllers;

class ExampleController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    //
}

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PartnerController extends Controller
{
    //
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        return view('pages.project', [
            'name' => 'project',
            'project' => $project,
        ]);
    }


    /**
     * Display the specified resource by slug.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function slug(Request $request, $project_slug)
    {
        $validator = Validator::make(['slug' => $project_slug], [
            'slug' => 'required|string|exists:projects,slug|max:255',
        ]);

        if($validator->fails()){
            abort(404);
        }

        $project = Project::where('slug', $project_slug)->firstOrFail();
        // dd($project->description);

        return view('pages.project', [
            'name' => 'project',
            'project' => $project,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }
}

app/Http/Controllers/PublicPagesController.php
<?php

namespace App\Http\Controllers;

use App\Partner;
use App\Project;
use App\Photo;

class PublicPagesController extends Controller
{
    public function home(){
    
        return view('pages.home', ['name' => 'home']);
        
    }

    public function portfolio(){

        return view('pages.portfolio', [
        	'name' => 'portfolio',
        	// 'projects' => Project::with('partner')->get(),
        	'partners' => Partner::orderBy('order')->get(),
        ]);
        
    }

    public function resume(){
    
        return view('pages.resume', ['name' => 'resume']);
        
    }

    public function services(){
    
        return view('pages.services', ['name' => 'services']);
        
    }

    public function modeling(){

        return view('pages.modeling', [
            'name' => 'modeling',
            'photos' => Photo::all()
        ]);
    
    }
}

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Diego Ponciano - Helping You Succeed On Your Next Software Project</title>
	<meta name="description" content="You are close to getting the help you need for your next web development project. You will be able to rely on more than 7 years of intense and meaningful experience and use them to your advantage and project success. The best Laravel and Node.js development at your fingertips." />

	<meta name="keywords" content="Laravel Development, Custom Software, Custom Web Application, Laravel dedicated companies, Laravel Development Companies, Node.js custom development, Vue.js custom development">

	<link rel="canonical" href="https://poncianodiego.com/">

	<meta property="og:title" content="Software Developer Diego Ponciano" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://www.poncianodiego.com/" />
	<meta property="og:image" content="http://poncianodiego.com/assets/logo-og.jpg" />
	<meta property="og:description" content="You are close to getting the help you need for your next web development project. You will be able to rely on more than 7 years of intense and meaningful experience and use them to your advantage and project success. The best Laravel and Node.js development at your fingertips." />

	<meta name="twitter:card" content="summary">
	<meta name="twitter:description" content="You are close to getting the help you need for your next web development project. You will be able to rely on more than 7 years of intense and meaningful experience and use them to your advantage and project success. The best Laravel and Node.js development at your fingertips.">
	<meta name="twitter:title" content="Diego Ponciano: Helping You Succeed On Your Next Web Development Project!">

	<script type="application/ld+json">{"@context":"https:\/\/schema.org","@type":"WebSite","@id":"#website","url":"https:\/\/poncianodiego.com\/","name":"Diego Ponciano","potentialAction":{"@type":"SearchAction","target":"https:\/\/poncianodiego.com\/?s={search_term_string}","query-input":"required name=search_term_string"}}</script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-83490804-5"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-83490804-5');
	</script>

	<link href="https://fonts.googleapis.com/css?family=Lobster|Playfair+Display|Raleway" rel="stylesheet">
	<link rel="stylesheet" href="/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.12/css/lightgallery.css"/>
	<link rel="stylesheet" href="/css/app.css">
	@stack('styles')
</head>
<body>

@include('layout.header')

@yield('content')

@include('layout.footer')

<script src="/js/jquery.js"></script>
<script src="/js/popper.min.js"></script>
<script src="/js/bootstrap.min.js"></script>

@stack('scripts')

</body>
</html>

resources/views/layout/footer.blade.php
<footer class="container-fluid bg-dark">
	<div class="row px-2 py-4">
		<div class="col mt-3 text-center position-relative">
			<p class="white">info@poncianodiego.com</p>
			<p class="white mt-3">&copy; @php echo date("Y"); @endphp</p>
			<a class="position-absolute" style="top: 0; right: 10px;" href="https://www.upwork.com/fl/diegoponciano">
				<img style="width: 60px;" src="/img/upwork-logo.png" alt="Hire me on Upwork">
			</a>
		</div>
	</div>
</footer>

resources/views/layout/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light sticky-top bg-white">
  <a class="navbar-brand" href="/"><h1>Diego Ponciano</h1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavBar" aria-controls="mainNavBar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="mainNavBar">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item @if($name == 'home') active @endif">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item @if($name == 'portfolio') active @endif">
        <a class="nav-link" href="/portfolio">Portfolio</a>
      </li>
      <li class="nav-item @if($name == 'resume') active @endif">
        <a class="nav-link" href="/resume">Resume</a>
      </li>
      <li class="nav-item @if($name == 'services') active @endif">
        <a class="nav-link" href="/services">Services</a>
      </li>
    </ul>
  </div>
</nav>

resources/views/layout/thatsme.blade.php
<div class="row mt-5">
  <div class="col-8 col-md-3 mx-auto mb-5">
    <img class="img-fluid me-pic" src="/img/me.jpg" alt="">
  </div>
  <div class="col-md-9 my-auto pl-4">
    <h2>That's me!</h2>
    <p class="mb-5">I consider myself to be an interdisciplinary Senior Software Developer with experience in many fields of the development process. I can help you succeed in your next software development project by capitalizing on my extensive experience in many different projects of all sizes and tech stacks. Feel free to contact me about your project!</p>
  </div>
</div>

resources/views/pages/blog/index.blade.php
@extends('layout.app')

@section('content')
<div class="container">
	<div class="row">
	@foreach($partners as $partner)
		<div class="col-12 partner-row mb-4">
			<div class="row justify-content-md-center">
				<div class="col-12 text-center">
					<h2>
						@if($partner->isNone()) 
							Portfolio: 
						@else In collaboration with: 
							<a href="{{$partner->site_url}}" target="_blank">{{$partner->name}}</a>
						@endif
					</h2>
				</div>
				@foreach($partner->projects as $project)
					<div class="col-md-4 portfolio-item mt-4">
						<div class="content">
							<img class="img-fluid" src="{{$project->public_thumbnail}}" alt="">
							<div class="overlay open-modal" data-target="#{{$project->slug}}-modal">
								<a href="#" class="project-title">{{$project->short_name}}</a>
							</div>
						</div>
					</div>
				@endforeach

			</div>
		</div>
	@endforeach
	</div>
	<div class="row mt-5">
		<div class="col-8 col-md-3 mx-auto mb-5">
			<img class="img-fluid me-pic" src="/img/me.jpg" alt="">
		</div>
		<div class="col-md-9 my-auto">
			<h2>That's me!</h2>
			<p class="mb-5">I consider myself to be an interdisciplinary developer with courage to explore many fields, I believe in organization and discipline as the motor of my achievements. I have experience in PHP, Java and Javascript (server side and client side). I'll be pretty straightforward and efficient with wordpress and laravel projects because that's my area of expertise, however I'm not scared with any technology.</p>
		</div>
	</div>
</div>

@endsection

resources/views/pages/home.blade.php
@extends('layout.app')

@section('content')

<div class="container">
	<div class="row" style="min-height: 100vh;">
		<div class="col-md-6 mt-6">
		  	<div id="typed-strings1" style="display: none;">
		      <span>Need a hand with<br><strong>software development</strong>?</span>
		      <span>^500Ping me for a quote.</span>
		    </div>
		  	<div id="typed-strings2" style="display: none;">
		      	<span>
		      		<a target="_blank" href="mailto:jay.dee.force@gmail.com?subject=Hello I need help with a React Project">&middot; React</a> <br>
		      		<a target="_blank" href="mailto:jay.dee.force@gmail.com?subject=Hello I need help with a Django Project">&middot; Django</a> <br>
		      		<a target="_blank" href="mailto:jay.dee.force@gmail.com?subject=Hello I need help with a Laravel Project">&middot; Laravel</a> <br>
		      		<a target="_blank" href="mailto:jay.dee.force@gmail.com?subject=Hello I need help with a Vue.js Project">&middot; Vue.js</a> <br>
		      		<a target="_blank" href="mailto:jay.dee.force@gmail.com?subject=Hello I need help with a Node.js Project">&middot; Node.js</a> <br>
		      		<a target="_blank" href="mailto:jay.dee.force@gmail.com?subject=Hello I need help with a React Native Project">&middot; React Native</a> <br>
		      		<!-- <a target="_blank" href="mailto:jay.dee.force@gmail.com?subject=Hello I need help with a Wordpress Project">&middot; Wordpress</a> <br> -->
		      	</span>
		    </div>
			<h2><span id="typed1" style="white-space:pre;"></h2>
			<h2 class="tech-list"><span id="typed2"></h2>
		</div>
		<div class="col-md-6 mt-6">
			<div class="capture">
				<img class="img-fluid mt-2" src="/img/capture.png" alt="">
				<h2 class="capture-button mt-2"><a target="_blank" href="mailto:jay.dee.force@gmail.com?subject=Hello I need a Quote&body=Hello, I was wondering how much it would cost to {Your project or task description here}"" role="button">Get Quote</a></h2>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col mb-2">
			<div class="jumbotron">
				<p>Software development can be hard. If you have the right set up and the best development workflow, your project is guaranteed to become a solid system. However, this is achieved with a combination of expertise, hard work and adoption of proper standards. I have the experience your project needs to become a nice and robust system.</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 my-5 pb-4">
			<h1>Don't scroll here, don't be shy and ping me up for a quote.</h1>
			<p>I believe good communication is the basis of successful projects, don't be shy and ask me for a quote for your project. Even if you don't hire me, I will help you get a better idea for your project.</p>
		</div>
	</div>
	
</div>

@endsection

@push('scripts')
<script src="/js/typed.min.js"></script>
<script>
		
	$('.capture').hide();

	var typed1 = new Typed('#typed1', {
		stringsElement: '#typed-strings1',
		typeSpeed: 12,
		backSpeed: 0,
		backDelay: 500,
		startDelay: 500,
		loop: false,
		onComplete: function (self){
			$('.typed-cursor').addClass('d-none');
			initTyped2();
		}
	});

	function initTyped2(){

		var typed1 = new Typed('#typed2', {
	    stringsElement: '#typed-strings2',
		    typeSpeed: 12,
		    backSpeed: 0,
		    backDelay: 500,
		    startDelay: 500,
		    loop: false,
		    onComplete: function(){
		    	$('.capture').fadeIn(2000);
			}
		});
	}
</script>
@endpush

resources/views/pages/modeling.blade.php
@extends('layout.app')

@section('content')

<style>
	.embed-container { 
		position: relative; 
		padding-bottom: 56.25%; 
		height: 0; 
		overflow: hidden; 
		max-width: 100%;
	} 

	.embed-container iframe, .embed-container object, .embed-container embed { 
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%; 
	}
</style>

<div class="container mt-5">
	<div class="row">
		<div class="col-12 mb-4">
			<div class="row justify-content-md-center">
				<div id="lightgallery" class="text-center">
					@foreach($photos as $photo)
						<a href="storage/{{ $photo->url }}">
							<img style="max-width: 300px; width: 100%;" src="storage/{{ $photo->url }}" />
						</a>
					@endforeach
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@push('scripts')

	<script>

		$('#lightgallery').lightGallery();

		$(".open-modal").on('click', function(){
			var target = $(this).data('target');
			$(target).modal('show');
			$(this).addClass('active');
		});

		$(".modal .close").on('click', function(){
			setTimeout(function(){
				$(".overlay").removeClass('active');
			}, 300);
		});

		$(".photo-show").slick();

		$('.modal').on('shown.bs.modal', function (e) {
		  $(this).find(".photo-show").slick('setPosition');
		})

	</script>

@endpush

resources/views/pages/portfolio.blade.php
@extends('layout.app')

@section('content')

<style>
	.embed-container { 
		position: relative; 
		padding-bottom: 56.25%; 
		height: 0; 
		overflow: hidden; 
		max-width: 100%;
	} 

	.embed-container iframe, .embed-container object, .embed-container embed { 
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%; 
	}

	.btn.btn-dark{
	    color: #ffffff;
	    background-color: #202020;
	    border-color: #202020;
	}

	.btn.btn-dark:hover{
	    background-color: #ccc;
	    border-color: #ccc;
	}
</style>

<div class="container mt-5">
	<div class="row">
		<div class="col-md-12 text-center mb-2">
			<h1>PORTFOLIO</h1>
			<!-- <p class="d-none d-sm-block">Check some of the projects I've worked with:</p> -->
			<h2 class="d-block fs-24">Check some of the projects I've worked with:</h2>
			<!-- <p>"With the right setup everything is possible"</p> -->
		</div>
	</div>
	<div class="row">
		@foreach($partners as $partner)
			@if($partner->projects()->count())
				<div class="col-12 partner-row mb-4">
					<div class="row justify-content-md-center">
						<div class="col-12 text-center">
							<h2>		
								@if(!$partner->isNone()) In collaboration with: 
								<a href="{{$partner->site_url}}" target="_blank">{{$partner->name}}</a>
								@endif
							</h2>
						</div>
						@foreach($partner->projects()->published()->orderByDesc('updated_at')->get() as $project)
							<div class="col-md-6 portfolio-item mt-4">
								<div class="frame" style="border: 1px solid; padding: 15px; border-radius: 10px;">
									<div class="content">
										<img class="img-fluid w-100" src="{{$project->public_thumbnail}}" alt="">
										<div class="overlay open-modal text-center d-none d-sm-flex" data-target="#{{$project->slug}}-modal">
											<a target="_blank" href="{{$project->internal_url}}" class="project-title">{{$project->short_name}} <br><br><i style="font-size: 24px;" class="fas fa-external-link-alt"></i></a>
										</div>
									</div>
									<p class="mt-4 d-block d-sm-none" style="font-size: 20px;" target="_blank" href="{{$project->internal_url}}">{{$project->short_name}}</p>
									<a class="btn btn-gold btn-lg text-center d-block d-sm-none" style="font-size: 20px;" href="{{$project->internal_url}}">See case</a>
								</div>
							</div>
						@endforeach
					</div>
				</div>
			@endif
		@endforeach

<!-- 		<div class="col-sm-8 mx-auto mt-5">
			<div class="embed-container">
				<iframe src='https://www.youtube.com/embed/kDnkTGUc-yQ' frameborder='0' allowfullscreen></iframe>
			</div>
		</div> -->
	
		<div class="col-sm-12 text-center mt-5">

			<a href="/services" style="font-size: 24px;">SERVICES <i class="fas fa-arrow-circle-right"></i></a>
		</div>
	</div>
	@include('layout.thatsme')
</div>

@endsection

resources/views/pages/project.blade.php
@extends('layout.app')

@section('content')

<style>
	.embed-container { 
		position: relative; 
		padding-bottom: 56.25%; 
		height: 0; 
		overflow: hidden; 
		max-width: 100%;
	} 

	.embed-container iframe, .embed-container object, .embed-container embed { 
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%; 
	}
</style>

<div class="container mt-5">
	<div class="row">	
		<div class="col-sm-12 text-center ">
			<h1>{{$project->short_name}}</h1>
		</div>
		<div class="col-12 d-block d-sm-none text-center mt-5">
			<p style="white-space: pre-line" class="fs-24">{{$project->description}}</p>
		</div>
		<div class="col-12 col-md-7 photo-show mt-5">
    	@foreach($project->images()->orderByDesc('created_at')->get() as $image)
				<img class="mb-4 gallery-item" src="{{$image->public_url}}" alt="">
			@endforeach
    </div>
		<div class="col-12 col-md-5 text-center mt-2 mt-sm-5">
			<p class="d-none d-sm-block" style="white-space: pre-line">
				{{$project->description}}
				@if($project->url)

				<a target="_blank" href="{{$project->url}}">Visit live project <i class="fas fa-external-link-alt"></i></a>
				@endif

				<a href="{{route('portfolio')}}"><i class="fas fa-arrow-circle-left"></i> See more projects</a>
	    	</p>
	    	<p style="white-space: pre-line" class="d-block d-sm-none fs-24">
	    		@if($project->url)
				<a target="_blank" href="{{$project->url}}">Visit live project <i class="fas fa-external-link-alt"></i></a>
				@endif

				<a href="{{route('portfolio')}}"><i class="fas fa-arrow-circle-left"></i> See more projects</a>
	    	</p>
		</div>
	</div>
	@include('layout.thatsme')
</div>

@endsection

@push('scripts')

	<script>

	</script>

@endpush

resources/views/pages/resume.blade.php
@extends('layout.app')
@section('content')
<div class="jumbotron m-0">
	<h1 class="display-4">Diego Ponciano</h1>
	<p class="lead">Software Engineer</p>
	<hr class="my-4">
	<p>Senior Full Stack Software Engineer with 7 years of intense and meaninful experience in the industry. Experienced in all stages of the development cycle for complex dynamic web projects, from small to enterprise scale. With a focus for strong, long term relationships with clients.</p>
	<div class="row">
		<div class="col-12 text-center">
			<h2 class="mb-4">Experience (most relevant clients):</h2>
		</div>
		<div class="col-12 col-lg-8 mx-auto">
			<table class="table table-striped">
				<tbody>
					<tr>
						<th style="width: 30%" scope="row">T2 (San Francisco, CA) 2022 - present</th>
						<td>T2 is a public social media platform with a waiting list of around 15K users and with hopes to scale largely. My role at T2 is planning and architechting existing and future solutions to scale and maitain our product services active and reliable. Help develop and maintain features and fix issues. Coordinate team members to best address the system needs and cooperate with engineers to solve and scale.</td>
			    </tr>
					<tr>
						<th style="width: 30%" scope="row">Havona (Australia and Singapore) 2021 - 2022</th>
						<td>Havona is a web and mobile social network with intentions to launch in Australia and the European market. My role here was as a Principal Software Engineer, helping manage, architect and maintain features with small yet very talented team of developers.</td>
			    </tr>
					<tr>
						<th style="width: 30%" scope="row">Mai36 Art Gallery (Zurich, Switzerland) 2020 - present</th>
						<td>My role here is to push new features and maintain existing ones. Also keep their systems updated and upgraded. We have added many new features to the website and many more are coming.</td>
			    </tr>
					<tr>
						<th style="width: 30%" scope="row">Mike's Bikes (SF, USA)<br> 2020 - present</th>
						<td>Built a full stack system for internal use as a contractor. The system provides an easy to use interface for technicians to track their time and materials used. Laravel and Vue.js was used.</td>
			    </tr>
					<tr>
						<th style="width: 30%" scope="row">LinkingArts (New Orleans, USA) 2019</th>
						<td>Provided advise for existing systems improvements and refactoring. Helped align to Laravel standards, helped on most parts of development cycle including QA on various web projects. </td>
			    </tr>
					<tr>
						<th style="width: 30%" scope="row">Modpart (California, USA) 2018</th>
						<td>Full stack developer, analyst and adviser. We developed
						a powerful web application based on Elastic Search, Laravel
						and Vue.js for a niche business opportunity. </td>
			    </tr>
					<tr>
						<th style="width: 30%" scope="row">Synapse Tech (Cambridge, UK) 2018</th>
						<td>Lead developer, technology advisor, quality assurance and front line developer. My main job was to build and maintain features and fix bugs across a very complex system, which we built from scratch. The project has been suspended by the founders.</td>
			    </tr>
					<tr>
						<th style="width: 30%" scope="row">Sporta Gym (Guatemala, Guatemala City) 2017</th>
						<td>Guatemalan Gym chain, they required advice, maitenance and development for their web systems (public and internal).</td>
			    </tr>
					<tr>
						<th style="width: 30%" scope="row">Telus International (Guatemala, Guatemala City) 2016</th>
						<td>Customer Service for a technology company based on San Franscisco, CA. My roles were CSR for 8 months, Trainer Mentor for 8 months and Supervisor for over a year. My responsibilities were, ensuring performance of a team of more than 16 agents and provide timely feedback for service improvement.</td>
			    </tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-12 text-center">
			<h2 class="mb-4">Studies:</h2>
		</div>
		<div class="col-12 col-lg-8 mx-auto">
			<table class="table">
				<tbody>
					<tr>
						<th style="width: 40%" scope="row">Systems Engineering (2014 - 2016)</th>
						<td>Mariano Galvez University</td>
			    	</tr>
					<tr>
						<th style="width: 40%" scope="row">High School (2009 - 2013)</th>
						<td>Valles School</td>
			    	</tr>
					
				</tbody>
			</table>
		</div>
<!-- 		<div class="col-12 text-right mt-4">
			<p class="lead">
				<a class="btn btn-gold btn-lg" href="/Diego Ponciano - Software Engineer - Light Resume.pdf" download role="button">Download</a>
			</p>
		</div> -->
	</div>
</div>


@endsection